### PR TITLE
Added entries to multiple categories.

### PR DESCRIPTION
**Pull request by aerosol-can**

### CODE REVIEW

**Comment by noraj** [comment]
please rebase your branch

**Comment by aerosol-can** [comment]
please review the changes.

**Comment by aerosol-can** [comment]
can you also please remove the `invalid` label?

**Comment by aerosol-can** [comment]
hey @noraj, I would really appreciate you reviewing my PR before 31st of October.

**Comment by noraj** [comment]
- [x] Squash merged https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/merge_requests/371/diffs?commit_id=7cc6c32b5bb2e882aa0a9ac71aa9950ec097cc0f since your branch contains 24 commits
- [x] Fixed format and syntax https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/merge_requests/371/diffs?commit_id=d4d2f8394d25ae13293426ebf996ae8ed27dcb0c

**Pull request closed without merging**
